---
title: "PFE2"
author: "Rick Morales"
date: "`r Sys.Date()`"
output: pdf_document
---


# Libraries and Data
```{r}
library(haven)
library(gtsummary)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(naniar)
library(tidyr)
library(glmnet)
library(randomForest)
library(SPlit)
library(parameters)
library(see)
library(caret)
library(factoextra)

brfss_2017 <- read_xpt("LLCP2017.XPT")

head(brfss_2017)

colnames(brfss_2017)
```


# Pre-Processing

### Additional Cleaning
```{r}
brfss_2017_cleaned <- brfss_2017 %>%
    select(-c(2:6), -c(10:27), -31, -37, -40, -45, -c(53:57), -c(62:64), -72, -c(80:82), -85, -c(87:89), -c(97:102), -106, -108, -110, -c(112:246), ... = -c(255:258), -c(326:327), -c(330:337), -c(340:345), -c(356:357))

head(brfss_2017_cleaned)
```

### Renaming Variables
```{r}
names(brfss_2017_cleaned)[1] <- "STATE"
names(brfss_2017_cleaned)[4] <- "PSU"
names(brfss_2017_cleaned)[8] <- "HLTHPLN"
names(brfss_2017_cleaned)[9] <- "PERSDOC"
names(brfss_2017_cleaned)[11] <- "CHECKUP"
names(brfss_2017_cleaned)[12] <- "BPHIGH"
names(brfss_2017_cleaned)[13] <- "CHOLCHK"
names(brfss_2017_cleaned)[14] <- "TOLDHI"
names(brfss_2017_cleaned)[15] <- "CVDINFR"
names(brfss_2017_cleaned)[16] <- "CVDCRHD"
names(brfss_2017_cleaned)[17] <- "CVDSTRK"
names(brfss_2017_cleaned)[18] <- "ASTHMA"
names(brfss_2017_cleaned)[21] <- "CHCCOPD"
names(brfss_2017_cleaned)[22] <- "HAVARTH"
names(brfss_2017_cleaned)[23] <- "ADDEPEV"
names(brfss_2017_cleaned)[25] <- "DIABETES"
names(brfss_2017_cleaned)[29] <- "RENTHOME"
names(brfss_2017_cleaned)[30] <- "VETERAN"
names(brfss_2017_cleaned)[31] <- "EMPLOYED"
names(brfss_2017_cleaned)[33] <- "INCOME"
names(brfss_2017_cleaned)[35] <- "WEIGHT"
names(brfss_2017_cleaned)[36] <- "HEIGHT"
names(brfss_2017_cleaned)[44] <- "USENOW"
names(brfss_2017_cleaned)[47] <- "FRUIT"
names(brfss_2017_cleaned)[48] <- "FRUIT_JUICE"
names(brfss_2017_cleaned)[49] <- "GREEN_VEG"
names(brfss_2017_cleaned)[50] <- "FRENCHF"
names(brfss_2017_cleaned)[51] <- "POTATO"
names(brfss_2017_cleaned)[52] <- "OTHER_VEG"
names(brfss_2017_cleaned)[53] <- "EXERCISE_ANY"
names(brfss_2017_cleaned)[56] <- "FLUSHOT"
names(brfss_2017_cleaned)[57] <- "PNEUMONIA_VAC"
names(brfss_2017_cleaned)[58] <- "HIVTEST"
names(brfss_2017_cleaned)[59] <- "HIVRISK"
names(brfss_2017_cleaned)[63] <- "STSTR"
names(brfss_2017_cleaned)[64] <- "STRATUM_WGHT"
names(brfss_2017_cleaned)[65] <- "RAWRAKE"
names(brfss_2017_cleaned)[66] <- "WT2RAKE"
names(brfss_2017_cleaned)[67] <- "IMPRACE"
names(brfss_2017_cleaned)[68] <- "DUALUSE"
names(brfss_2017_cleaned)[69] <- "DUALCOR"
names(brfss_2017_cleaned)[70] <- "LLCPWT2"
names(brfss_2017_cleaned)[71] <- "LLCPWT"
names(brfss_2017_cleaned)[72] <- "RFHLTH"
names(brfss_2017_cleaned)[73] <- "PHYS_COMP"
names(brfss_2017_cleaned)[74] <- "MENT_COMP"
names(brfss_2017_cleaned)[75] <- "HCVU651"
names(brfss_2017_cleaned)[76] <- "RFHYPES"
names(brfss_2017_cleaned)[77] <- "CHOLCH1"
names(brfss_2017_cleaned)[78] <- "HICHOL_COMP"
names(brfss_2017_cleaned)[79] <- "MI_CHD"
names(brfss_2017_cleaned)[80] <- "ASTHMA_LIFE"
names(brfss_2017_cleaned)[81] <- "ASTHMA_NOW_COMP"
names(brfss_2017_cleaned)[82] <- "ASTHMA_COMP"
names(brfss_2017_cleaned)[83] <- "ARTHRITIS_DIAGNOS"
names(brfss_2017_cleaned)[84] <- "LIMIT_ACTIVITY"
names(brfss_2017_cleaned)[85] <- "LIMIT_WORK"
names(brfss_2017_cleaned)[86] <- "LIMIT_SOCIAL"
names(brfss_2017_cleaned)[87] <- "PRACE_COMP"
names(brfss_2017_cleaned)[88] <- "MULTI_RACE"
names(brfss_2017_cleaned)[89] <- "HISPANIC_COMP"
names(brfss_2017_cleaned)[90] <- "RACE_COMP"
names(brfss_2017_cleaned)[91] <- "RACEG21"
names(brfss_2017_cleaned)[92] <- "RACEGR3"
names(brfss_2017_cleaned)[93] <- "RACE_G1"
names(brfss_2017_cleaned)[94] <- "AGEG5YR"
names(brfss_2017_cleaned)[95] <- "AGE65YR"
names(brfss_2017_cleaned)[96] <- "AGE80"
names(brfss_2017_cleaned)[97] <- "AGE_G"
names(brfss_2017_cleaned)[98] <- "HT_COMP_IN"
names(brfss_2017_cleaned)[99] <- "HT_COMP_M"
names(brfss_2017_cleaned)[100] <- "WT_COMP_KILO"
names(brfss_2017_cleaned)[101] <- "BMI"
names(brfss_2017_cleaned)[102] <- "BMI_CAT"
names(brfss_2017_cleaned)[103] <- "BMI_OVER"
names(brfss_2017_cleaned)[104] <- "CHILD_COMP"
names(brfss_2017_cleaned)[105] <- "EDUCA_COMP"
names(brfss_2017_cleaned)[106] <- "INCOME_COMP"
names(brfss_2017_cleaned)[107] <- "SMOKER_COMP"
names(brfss_2017_cleaned)[108] <- "SMOKENOW_COMP"
names(brfss_2017_cleaned)[109] <- "ECIG_COMP"
names(brfss_2017_cleaned)[110] <- "ECIG_NOW_COMP"
names(brfss_2017_cleaned)[111] <- "DRINKANY_30"
names(brfss_2017_cleaned)[112] <- "DROCDY3"
names(brfss_2017_cleaned)[113] <- "BINGE_COMP"
names(brfss_2017_cleaned)[114] <- "WEEKLY_DRINK"
names(brfss_2017_cleaned)[115] <- "HEAVY_DRINK"
names(brfss_2017_cleaned)[116] <- "FRUITJUICE_COMP"
names(brfss_2017_cleaned)[117] <- "FRUITJUICE_COMP2"
names(brfss_2017_cleaned)[118] <- "GREEN_VEG_COMP"
names(brfss_2017_cleaned)[119] <- "FRENCHF_COMP"
names(brfss_2017_cleaned)[120] <- "POTATO_COMP"
names(brfss_2017_cleaned)[121] <- "OTHER_VEG_COMP"
names(brfss_2017_cleaned)[122] <- "MISSING_FRUIT"
names(brfss_2017_cleaned)[123] <- "MISSING_VEG"
names(brfss_2017_cleaned)[124] <- "MISS_ANY_FRUIT"
names(brfss_2017_cleaned)[125] <- "MISS_ANY_VEG"
names(brfss_2017_cleaned)[126] <- "TOTAL_FRUIT"
names(brfss_2017_cleaned)[127] <- "TOTAL_VEG"
names(brfss_2017_cleaned)[128] <- "ATLEAST1_FRUIT"
names(brfss_2017_cleaned)[129] <- "ATLEAST1_VEG"
names(brfss_2017_cleaned)[130] <- "MORE16_FRUIT"
names(brfss_2017_cleaned)[131] <- "MORE23_VEG"
names(brfss_2017_cleaned)[132] <- "FRUIT_EXCLUDE"
names(brfss_2017_cleaned)[133] <- "VEG_EXCLUDE"
names(brfss_2017_cleaned)[134] <- "LEISURE_COMP"
names(brfss_2017_cleaned)[135] <- "MAX_OXYGEN"
names(brfss_2017_cleaned)[136] <- "FUNC_CAPACITY"
names(brfss_2017_cleaned)[137] <- "STRENGTH_FREQ"
names(brfss_2017_cleaned)[138] <- "MISSING_PHYS"
names(brfss_2017_cleaned)[139] <- "PHYS_CATEGORY"
names(brfss_2017_cleaned)[140] <- "PHYS_IDX"
names(brfss_2017_cleaned)[141] <- "150_PHYS_COMP"
names(brfss_2017_cleaned)[142] <- "300_PHYS_COMP"
names(brfss_2017_cleaned)[143] <- "300_PHYS2_COMP"
names(brfss_2017_cleaned)[144] <- "MUSCLE_RECOMMEND"
names(brfss_2017_cleaned)[145] <- "AEROBIC_STRENGTH"
names(brfss_2017_cleaned)[146] <- "AEROBIC_STRENGTH2"
names(brfss_2017_cleaned)[147] <- "SEATBELT_COMP"
names(brfss_2017_cleaned)[148] <- "SEATBELT_COMP2"
names(brfss_2017_cleaned)[149] <- "AIDSTEST_COMP"
```


# Missing Data Summary Table
```{r}
missing_summary <- brfss_2017_cleaned %>%
  miss_var_summary()

print(missing_summary)
```


# Value Imputation and Feature Creation
```{r}
brfss_2017_cleaned[is.na(brfss_2017_cleaned)] <- 0

colSums(is.na(brfss_2017_cleaned))

df <- brfss_2017_cleaned %>%
  filter(!is.na(ECIG_COMP)) %>%
  mutate(VapeStatus = factor(ECIG_COMP,
    levels = c(1, 2, 3, 4, 9),
    labels = c("Current User", "Current User", "Former User", "Never Used", "No Response")))

# Recode STATE column
df$STATE_ABBR <- recode(df$STATE,
                       '1' = 'AL',
                       '2' = 'AK',
                       '4' = 'AZ',
                       '5' = 'AR',
                       '6' = 'CA',
                       '8' = 'CO',
                       '9' = 'CT',
                       '10' = 'DE',
                       '11' = 'DC',
                       '12' = 'FL',
                       '13' = 'GA',
                       '15' = 'HI',
                       '16' = 'ID',
                       '17' = 'IL',
                       '18' = 'IN',
                       '19' = 'IA',
                       '20' = 'KS',
                       '21' = 'KY',
                       '22' = 'LA',
                       '23' = 'ME',
                       '24' = 'MD',
                       '25' = 'MA',
                       '26' = 'MI',
                       '27' = 'MN',
                       '28' = 'MS',
                       '29' = 'MO',
                       '30' = 'MT',
                       '31' = 'NE',
                       '32' = 'NV',
                       '33' = 'NH',
                       '34' = 'NJ',
                       '35' = 'NM',
                       '36' = 'NY',
                       '37' = 'NC',
                       '38' = 'ND',
                       '39' = 'OH',
                       '40' = 'OK',
                       '41' = 'OR',
                       '42' = 'PA',
                       '44' = 'RI',
                       '45' = 'SC',
                       '46' = 'SD',
                       '47' = 'TN',
                       '48' = 'TX',
                       '49' = 'UT',
                       '50' = 'VT',
                       '51' = 'VA',
                       '53' = 'WA',
                       '54' = 'WV',
                       '55' = 'WI',
                       '56' = 'WY',
                       '66' = 'GU',
                       '72' = 'PR')
```


# Train-Test Split Ratio
```{r}
df <- df %>%
  filter(ASTHMA_NOW_COMP == 1)

# Use updated predictor set per professor feedback
predictors <- c('AGE80', 'BMI', 'SMOKER_COMP', 'STATE', 'ADDEPEV', 'CHCCOPD', 'CHECKUP', 'GENHLTH', 'HLTHPLN', 'EDUCA_COMP', 'INCOME_COMP', 'SEX', 'WEEKLY_DRINK')

x <- data.matrix(df[, predictors])
y <- df$ECIG_COMP
data <- data.frame(x, y)

model <- lm(y ~ ., data = data)
plot(model)

result <- model_parameters(model)
result
plot(result)

coefficients <- coef(model)
slope <- coefficients[2]
intercept <- coefficients[1]

predictions <- predict(model, newdata = data.frame(x))
actual_values <- data$y
squared_error_loss <- sum((actual_values - predictions)^2)
mse <- mean((actual_values - predictions)^2)
mse

cv_model <- cv.glmnet(x, y, alpha = 1)
plot(cv_model)

random_values <- rnorm(n = nrow(df), mean = 0, sd = 1)
optimal_ratio <- splitratio(random_values, y, method = "regression")
optimal_ratio

set.seed(123)
split <- sort(sample(nrow(df), nrow(df) * 0.6))
train <- df[split, ]
test <- df[-split, ]

calcSplitRatio <- function(p = NA, df) {
  if (is.na(p)) {
    p <- ncol(df) - 1
  }
  test_prop <- round((1 / sqrt(p)), 2)
  train_prop <- 1 - test_prop

  print(paste0("The ideal split ratio is ", train_prop, ":", test_prop, " training:testing"))

  set.seed(123)
  sample_index <- sample(seq_len(nrow(df)), size = floor(train_prop * nrow(df)))
  train <- df[sample_index, ]
  test <- df[-sample_index, ]

  return(list(
    train_prop = train_prop,
    test_prop = test_prop,
    train = train,
    test = test
  ))
}

result <- calcSplitRatio(df = df)
```


# Encoding
```{r}
df <- df %>%
  select(-STATE_ABBR, -VapeStatus)
```


# Arithmetic Transformations
```{r}
df$log_x <- log(df$ECIG_COMP)
df$sqrt_x <- sqrt(df$ECIG_COMP)
```


# Normalize and/or Scale
```{r}
preprocessed_data <- preProcess(df[, c('AGE80', 'BMI', 'SMOKER_COMP', 'STATE', 'ADDEPEV', 'CHCCOPD', 'CHECKUP', 'GENHLTH', 'HLTHPLN', 'EDUCA_COMP', 'INCOME_COMP', 'SEX', 'WEEKLY_DRINK', 'ECIG_COMP')], method = "range")
transformed_data <- predict(preprocessed_data, df)
print(transformed_data)
```


# PCA (Unsupervised) Feature Engineering
```{r}
numerical_data <- transformed_data %>%
  select(where(is.numeric)) %>%
  select(where(~ var(.x, na.rm = TRUE) != 0))

numerical_data <- numerical_data %>%
  filter_all(all_vars(is.finite(.))) %>%
  na.omit()

pca <- princomp(numerical_data)
summary(pca)
pca$loadings[, 1:2]
fviz_eig(pca, addlabels = TRUE)
```


# K-Means Clustering (Unsupervised)
```{r}
kmeans_data <- transformed_data %>%
  select(where(is.numeric)) %>%
  select(where(~ var(.x, na.rm = TRUE) != 0)) %>%
  na.omit()

set.seed(123)
kmeans_result <- kmeans(kmeans_data, centers = 3, nstart = 25)

fviz_cluster(kmeans_result, 
             data = kmeans_data,
             palette = c("red", "blue", "green"),
             geom = "point",
             pointsize = 1.2,
             ellipse.type = "t",
             show.clust.cent = TRUE,
             ggtheme = theme_minimal()) +
  labs(title = "K-Means Clustering of BRFSS Data (k = 3)")

kmeans_data$Cluster <- as.factor(kmeans_result$cluster)

kmeans_data %>%
  group_by(Cluster) %>%
  summarise(across(c(AGE80, BMI, WEEKLY_DRINK), mean, na.rm = TRUE))
```




